
services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./database_data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  php:
    build:
      context: ./docker/
      dockerfile: php-fpm.dockerfile
    image: php:8.3-fpm-alpine
    container_name: symfony_php
    volumes:
      - .:/var/www/html # Montre le projet Symfony dans PHP (accessible à Symfony)
    depends_on:
      - database

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
